### PR TITLE
Test unix socket based tigervnc

### PR DESCRIPTION
**Pull request by pnasrat**

### CODE REVIEW

**Comment by pnasrat** [comment]
@volcanocyber this is ready to merge, while I have firefox working with the last image locally something is causing the entire VNC server/proxying to throw an error so I want to test with the latest upstream changes in jupyter-remote-desktop-proxy

**Comment by volcanocyber** [comment]
@pnasrat Just to clarify, the last image had firefox working, but tigervnc was having problems? So with this PR using juypter-remote-desktop-proxy both should be ok, correct? Thanks so much.

**Comment by pnasrat** [comment]
The image works when run locally using docker, I am trying to diagnose why it is not working on the hub. There are a number of parts to this which have had bugs issues for using tigervnc in jupyter. I'm doing the best I can to try figure it out. I want to see if what I suspect fixes it does running on kubernetes however to accurately test that needs to be done using your image as there are many variables.

I am not saying it is fixed at this time

**Comment by pnasrat** [comment]
A brief update I was able to test on the staging hub with the update that this PR pulls in and it appears to fix the issues with the stack to serve a VNC hosted desktop and firefox starts fine. Please merge

**Pull request merged**
